"""
Generate derived website assets:

1. One WPF-friendly `thumbnail.webp` per published entry.
2. Static detail pages at /builds/<slug>/ and /prefabs/<slug>/.

The source of truth remains website/data/<dataset>/<slug>/build.json and each
dataset's index.json. Hidden entries can remain in data folders; they only get
public pages when listed in index.json.
"""
from __future__ import annotations

import html
import json
import shutil
import sys
from pathlib import Path

from PIL import Image, ImageOps

REPO = Path(__file__).resolve().parents[1]
WEBSITE = REPO / "website"
DATA = WEBSITE / "data"
DATASETS = ("builds", "prefabs")
THUMBNAIL_NAME = "thumbnail.webp"
THUMBNAIL_MAX_SIZE = (1024, 1024)
THUMBNAIL_QUALITY = 82
GENERATED_MARKER = "<!-- generated by tools/generate_site_assets.py -->"


def rel_web(path: Path) -> str:
    return "/" + path.relative_to(WEBSITE).as_posix()


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def visible_slugs(dataset: str) -> list[str]:
    idx = read_json(DATA / dataset / "index.json")
    entries = idx.get("entries") or idx.get(dataset) or []
    return [str(slug) for slug in entries]


def all_entry_dirs(dataset: str) -> list[Path]:
    root = DATA / dataset
    if not root.is_dir():
        return []
    return sorted(p for p in root.iterdir() if p.is_dir())


def write_all_entries_index(dataset: str, visible: set[str]) -> int:
    entries = []
    for folder in all_entry_dirs(dataset):
        row = {
            "slug": folder.name,
            "visible": folder.name in visible,
        }
        card_path = folder / "build.json"
        if card_path.is_file():
            try:
                card = read_json(card_path)
                row["name"] = str(card.get("name") or folder.name)
                row["published_unix"] = int(card.get("published_unix") or 0)
            except (OSError, ValueError, TypeError):
                row["name"] = folder.name
                row["published_unix"] = 0
        entries.append(row)

    entries.sort(key=lambda row: (not row["visible"], str(row.get("name") or row["slug"]).lower(), row["slug"]))
    write_json(DATA / dataset / "all.json", {"entries": entries})
    return len(entries)


def clean_images_list(card: dict) -> list[str]:
    raw = card.get("images")
    images: list[str] = []
    if isinstance(raw, list):
        for item in raw:
            if not isinstance(item, str) or not item:
                continue
            if item == THUMBNAIL_NAME:
                continue
            if item not in images:
                images.append(item)

    current_image = card.get("image")
    if not images and isinstance(current_image, str) and current_image and current_image != THUMBNAIL_NAME:
        images.append(current_image)
    return images


def generate_thumbnail(folder: Path, source_name: str) -> bool:
    source = folder / source_name
    if not source.is_file():
        print(f"  [WARN] missing thumbnail source: {source.relative_to(REPO)}")
        return False

    target = folder / THUMBNAIL_NAME
    try:
        with Image.open(source) as img:
            img = ImageOps.exif_transpose(img)
            if img.mode not in ("RGB", "RGBA"):
                img = img.convert("RGB")
            img.thumbnail(THUMBNAIL_MAX_SIZE, Image.Resampling.LANCZOS)
            img.save(target, "WEBP", quality=THUMBNAIL_QUALITY, method=6)
    except OSError as exc:
        print(f"  [WARN] could not generate thumbnail for {source.relative_to(REPO)}: {exc}")
        return False
    return True


def update_card_thumbnail(dataset: str, folder: Path) -> bool:
    card_path = folder / "build.json"
    if not card_path.is_file():
        return False

    card = read_json(card_path)
    images = clean_images_list(card)
    changed = False

    if images != card.get("images"):
        card["images"] = images
        changed = True

    if images:
        if generate_thumbnail(folder, images[0]):
            if card.get("image") != THUMBNAIL_NAME:
                card["image"] = THUMBNAIL_NAME
                changed = True
    else:
        print(f"  [WARN] {dataset}/{folder.name} has no full-size images list; image left unchanged")

    if changed:
        write_json(card_path, card)
    return changed


def page_title(dataset: str) -> str:
    return "Builds" if dataset == "builds" else "Prefabs"


def detail_html(dataset: str, slug: str) -> str:
    folder = DATA / dataset / slug
    card = read_json(folder / "build.json")
    name = str(card.get("name") or slug)
    desc = str(card.get("description") or "")
    image = card.get("image")
    image_url = rel_web(folder / image) if isinstance(image, str) and image else "/shared/assets/logo.png"
    title = f"{name} - RSDWBuilds.com"
    return f"""<!DOCTYPE html>
{GENERATED_MARKER}
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{html.escape(title)}</title>
  <meta name="description" content="{html.escape(desc)}" />
  <meta property="og:title" content="{html.escape(title)}" />
  <meta property="og:description" content="{html.escape(desc)}" />
  <meta property="og:image" content="{html.escape(image_url)}" />
  <link rel="apple-touch-icon" sizes="180x180" href="/shared/assets/favicon_io/apple-touch-icon.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="/shared/assets/favicon_io/favicon-32x32.png" />
  <link rel="icon" type="image/png" sizes="16x16" href="/shared/assets/favicon_io/favicon-16x16.png" />
  <link rel="icon" href="/shared/assets/favicon_io/favicon.ico" />
  <link rel="manifest" href="/shared/assets/favicon_io/site.webmanifest" />
  <link rel="preload" href="https://fonts.gstatic.com/s/sofiasans/v20/Yq6T-LCVXSLy9uPBwlATrORKkzApcb8.woff2" as="font" type="font/woff2" crossorigin />
  <link rel="stylesheet" href="/shared/site-shell.css" />
  <link rel="stylesheet" href="/shared/detail.css" />
</head>
<body data-tool="{html.escape(dataset)}">
  <div id="rsdw-header-mount"></div>

  <main class="rsdw-detail" id="rsdw-detail">
    <p class="rsdw-empty">Loading {html.escape(page_title(dataset).lower())}...</p>
  </main>

  <div id="rsdw-footer-mount"></div>

  <script>
    window.RSDW_DETAIL_CONFIG = {{
      dataset: "{html.escape(dataset)}",
      slug: "{html.escape(slug)}"
    }};
  </script>
  <script src="/shared/shared-header.js" defer></script>
  <script src="/shared/detail.js" defer></script>
</body>
</html>
"""


def write_detail_page(dataset: str, slug: str) -> None:
    out_dir = WEBSITE / dataset / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index.html").write_text(detail_html(dataset, slug), encoding="utf-8")


def remove_stale_pages(dataset: str, visible: set[str]) -> None:
    root = WEBSITE / dataset
    if not root.is_dir():
        return
    for child in root.iterdir():
        if not child.is_dir() or child.name in visible:
            continue
        index = child / "index.html"
        try:
            text = index.read_text(encoding="utf-8")
        except OSError:
            continue
        if GENERATED_MARKER in text:
            shutil.rmtree(child)
            print(f"  removed stale page {child.relative_to(REPO)}")


def main() -> int:
    for dataset in DATASETS:
        print(f"[{dataset}]")
        visible = set(visible_slugs(dataset))
        changed_cards = 0
        for folder in all_entry_dirs(dataset):
            if update_card_thumbnail(dataset, folder):
                changed_cards += 1

        for slug in sorted(visible):
            folder = DATA / dataset / slug
            if not (folder / "build.json").is_file():
                print(f"  [WARN] visible slug missing build.json: {dataset}/{slug}")
                continue
            write_detail_page(dataset, slug)

        registry_count = write_all_entries_index(dataset, visible)
        remove_stale_pages(dataset, visible)
        print(f"  thumbnails/metadata updated: {changed_cards}; detail pages: {len(visible)}; registry entries: {registry_count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
